
# app/repositories/interfaces/task.py
from typing import Protocol, List, Optional
from app.models.comment import Comment
from app.schemas.comment import TaskComment, TaskCommentResponse

class AbstractCommentRepository(Protocol):
    async def get_by_id(self, task_id: int, comment_id: int) -> Optional[TaskComment]: ...
    async def get_all(self) -> List[TaskComment]: ...
    async def create(self, task_in: TaskComment) -> TaskComment: ...
    async def delete(self, task_id: int) -> bool: ...
    async def enrich_tasks_with_usernames(self, tasks: List[TaskComment]) -> List[dict]: ...